#!/bin/bash 
echo "Start Deploy Now" && sleep 30 
echo "1 Circleci.....BROO" && sleep 30
echo "2 Circleci.....BROO" && sleep 30
echo "3 Circleci.....BROO" && sleep 30
echo "4 Circleci.....BROO" && sleep 30
echo "5 Circleci.....BROO" && sleep 30
echo "6 Circleci.....BROO" && sleep 30
echo "7 Circleci.....BROO" && sleep 30
echo "8 Circleci.....BROO" && sleep 30
echo "9 Circleci.....BROO" && sleep 30
echo "10 Circleci.....GOSI" && sleep 30
echo "1 Circleci.....BROO" && sleep 30
echo "2 Circleci.....BROO" && sleep 30
echo "3 Circleci.....BROO" && sleep 30
echo "4 Circleci.....BROO" && sleep 30
echo "5 Circleci.....BROO" && sleep 30
echo "6 Circleci.....BROO" && sleep 30
echo "7 Circleci.....BROO" && sleep 30
echo "8 Circleci.....BROO" && sleep 30
echo "9 Circleci.....BROO" && sleep 30
echo "10 Circleci.....GOSI" && sleep 30
echo "1 Circleci.....BROO" && sleep 30
echo "2 Circleci.....BROO" && sleep 30
echo "3 Circleci.....BROO" && sleep 30
echo "4 Circleci.....BROO" && sleep 30
echo "5 Circleci.....BROO" && sleep 30
echo "6 Circleci.....BROO" && sleep 30
echo "7 Circleci.....BROO" && sleep 30
echo "8 Circleci.....BROO" && sleep 30
echo "9 Circleci.....BROO" && sleep 30
echo "10 Circleci.....GOSI" && sleep 30
echo "1 Circleci.....BROO" && sleep 30
echo "2 Circleci.....BROO" && sleep 30
echo "3 Circleci.....BROO" && sleep 30
echo "4 Circleci.....BROO" && sleep 30
echo "5 Circleci.....BROO" && sleep 30
echo "6 Circleci.....BROO" && sleep 30
echo "7 Circleci.....BROO" && sleep 30
echo "8 Circleci.....BROO" && sleep 30
echo "9 Circleci.....BROO" && sleep 30
echo "10 Circleci.....GOSI" && sleep 30
echo "1 Circleci.....BROO" && sleep 30
echo "2 Circleci.....BROO" && sleep 30
echo "3 Circleci.....BROO" && sleep 30
echo "4 Circleci.....BROO" && sleep 30
echo "5 Circleci.....BROO" && sleep 30
echo "6 Circleci.....BROO" && sleep 30
echo "7 Circleci.....BROO" && sleep 30
echo "8 Circleci.....BROO" && sleep 30
echo "9 Circleci.....BROO" && sleep 30
echo "10 Circleci.....GOSI" && sleep 30
echo "1 Circleci.....BROO" && sleep 30
echo "2 Circleci.....BROO" && sleep 30
echo "3 Circleci.....BROO" && sleep 30
echo "4 Circleci.....BROO" && sleep 30
echo "5 Circleci.....BROO" && sleep 30
echo "6 Circleci.....BROO" && sleep 30
echo "7 Circleci.....BROO" && sleep 30
echo "8 Circleci.....BROO" && sleep 30
echo "9 Circleci.....BROO" && sleep 30
echo "Next Proses....BROO" && sleep 30 
echo "1 Circleci.....BROO" && sleep 30
echo "2 Circleci.....BROO" && sleep 30
echo "3 Circleci.....BROO" && sleep 30
echo "4 Circleci.....BROO" && sleep 30
echo "5 Circleci.....BROO" && sleep 30
echo "6 Circleci.....BROO" && sleep 30
echo "7 Circleci.....BROO" && sleep 30
echo "8 Circleci.....BROO" && sleep 30
echo "9 Circleci.....BROO" && sleep 30
echo "10 Circleci.....GOSI" && sleep 30
echo "1 Circleci.....BROO" && sleep 30
echo "2 Circleci.....BROO" && sleep 30
echo "3 Circleci.....BROO" && sleep 30
echo "4 Circleci.....BROO" && sleep 30
echo "5 Circleci.....BROO" && sleep 30
echo "6 Circleci.....BROO" && sleep 30
echo "7 Circleci.....BROO" && sleep 30
echo "8 Circleci.....BROO" && sleep 30
echo "9 Circleci.....BROO" && sleep 30
echo "10 Circleci.....GOSI" && sleep 30
echo "1 Circleci.....BROO" && sleep 30
echo "2 Circleci.....BROO" && sleep 30
echo "3 Circleci.....BROO" && sleep 30
echo "4 Circleci.....BROO" && sleep 30
echo "5 Circleci.....BROO" && sleep 30
echo "6 Circleci.....BROO" && sleep 30
echo "7 Circleci.....BROO" && sleep 30
echo "8 Circleci.....BROO" && sleep 30
echo "9 Circleci.....BROO" && sleep 30
echo "10 Circleci.....GOSI" && sleep 30
echo "1 Circleci.....BROO" && sleep 30
echo "2 Circleci.....BROO" && sleep 30
echo "3 Circleci.....BROO" && sleep 30
echo "4 Circleci.....BROO" && sleep 30
echo "5 Circleci.....BROO" && sleep 30
echo "6 Circleci.....BROO" && sleep 30
echo "7 Circleci.....BROO" && sleep 30
echo "8 Circleci.....BROO" && sleep 30
echo "9 Circleci.....BROO" && sleep 30
echo "10 Circleci.....GOSI" && sleep 30
echo "1 Circleci.....BROO" && sleep 30
echo "2 Circleci.....BROO" && sleep 30
echo "3 Circleci.....BROO" && sleep 30
echo "4 Circleci.....BROO" && sleep 30
echo "5 Circleci.....BROO" && sleep 30
echo "6 Circleci.....BROO" && sleep 30
echo "7 Circleci.....BROO" && sleep 30
echo "8 Circleci.....BROO" && sleep 30
echo "9 Circleci.....BROO" && sleep 30
echo "10 Circleci.....GOSI" && sleep 30
echo "1 Circleci.....BROO" && sleep 30
echo "2 Circleci.....BROO" && sleep 30
echo "3 Circleci.....BROO" && sleep 30
echo "4 Circleci.....BROO" && sleep 30
echo "5 Circleci.....BROO" && sleep 30
echo "6 Circleci.....BROO" && sleep 30
echo "7 Circleci.....BROO" && sleep 30
echo "8 Circleci.....BROO" && sleep 30
echo "9 Circleci.....BROO" && sleep 30
echo "Deploy & Build Sukses"
